server:
  error:
    include-stacktrace: on_trace_param

spring:
  jpa:
    open-in-view: false

management:
  cloudfoundry:
    skip-ssl-validation: true
#  endpoints:
#    web:
#      exposure: "*"

resourceServerUrl: ${RESOURCE_URL:https://resource-server.domain}